### Site info:
title: yukitaka.log
tagline: 
author: Yukitaka Ohmura
email: 
description: "まとまった文章を書くのに使っています。"
keywords: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yktko.github.io" # the base hostname & protocol for your site
locale: ja_JP

### Personal info and site tools info:
twitter_username: yktko
github_username:  yktko
facebook_username: yukitaka.ohmura
disqus_shortname: 
favicon: /images/favicon.ico
aboutme: クラウドのテクニカルトレーナー。日本酒とアウトドアとオープンソースとアジャイルが好き。興味：CloudStack/DevOps/スクラム/トロンボーン/カレー/唐揚げ/ちばらぎ/怪しい関西弁/富山。本ブログは個人の見解であり、所属企業の意見を代表するものではありません。
aboutme_photo: /images/mii_yom.png


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: yktk
      href: http://yktko.github.io
      title: yukitaka.log


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
permalink: /:year/:month/:day/:title
